object Versions {
    const val gson = "2.8.9"
    const val coreKtx = "1.12.0"
    const val lifecycle = "2.6.2"
    const val activityCompose = "1.7.2"
    const val composeBOM = "2023.03.00"
    const val ui = "ui"
    const val uiGraphics = "ui-graphics"
    const val material = "material3"
    const val nabigationRuntimeKtx = "2.7.3"
    const val jUnit = "4.13.2"
    const val androidJUnit = "1.1.5"
    const val espresso = "3.5.1"
    const val composeJUnit = "ui-test-junit4"
    const val composeUITooling = "ui-tooling"
    const val composeManifest = "ui-test-manifest"
}